# Generated by Django 4.1.7 on 2023-03-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_disital_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='StopAsyncIteration',
        ),
    ]
